version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@20
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Creating environment files..."
      - mkdir -p src/environments
      - |
        cat > src/environments/environment.ts << 'EOF'
        export const environment = {
          production: false,
          apiUrl: 'https://localhost:7124/api'
        };
        EOF
      - |
        cat > src/environments/environment.prod.ts << EOF
        export const environment = {
          production: true,
          apiUrl: '${API_URL}'
        };
        EOF
      - echo "Environment files created successfully"
      - cat src/environments/environment.prod.ts
      - ng version

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/UserCreationFront/browser'
